import { localizeConfigCopy, isZhCnConfigCopy } from "../i18n/lib/config-copy.ts";

const ZH_CN_OUI_COMPANY_COPY = {
  Company: "公司",
  Lobby: "大厅",
  Dashboard: "总看板",
  "Company dashboard": "公司总看板",
  "Company, tasks, and run timeline": "公司、任务和运行时间线",
  "OUI Company": "OUI 公司",
  "Refreshing...": "正在刷新...",
  Refresh: "刷新",
  "Four-pane chat": "四宫格聊天",
  Companies: "公司",
  "Your AI companies": "我的 AI 公司",
  "Company status": "公司状态",
  "New company": "新公司",
  "Company name": "公司名",
  "Create company": "创建公司",
  "Choose CEO": "选择 CEO",
  "Delete company": "删除公司",
  "Delete company {name}?": "删除公司“{name}”？",
  "Connect Gateway to choose CEO": "连接 Gateway 后选择 CEO",
  "Waiting for you": "待你处理",
  "Completed tasks": "已完成任务",
  "Token usage": "Token 消耗",
  "Last activity": "最近活动",
  CEO: "CEO",
  Stage: "阶段",
  Status: "状态",
  Mode: "模式",
  Inbox: "收件箱",
  "Not set": "未设置",
  "No active objective yet.": "还没有主线目标",
  "No companies yet.": "暂无公司",
  "Internal records": "内部记录",
  "Task workbench": "任务工作台",
  Audit: "审计",
  "Audit log": "审计日志",
  "No audit records yet.": "还没有审计记录。",
  Idle: "空闲",
  project: "项目型",
  routine: "常驻业务",
  idle: "空闲",
  waiting_user: "待你处理",
  "waiting user": "待你处理",
  paused: "暂停",
  Leader: "领导者",
  Tasks: "任务",
  Tokens: "Token",
  Runs: "运行",
  "OUI server": "OUI 服务",
  Connected: "已连接",
  Disconnected: "未连接",
  Unassigned: "未分配",
  Active: "启用",
  Executable: "可执行",
  Disabled: "已禁用",
  "OpenClaw-led agents": "OpenClaw 主导的 agent",
  "No agents yet.": "暂无 agent。",
  Task: "任务",
  "Create work": "创建工作",
  Title: "标题",
  Assignee: "负责人",
  "What should the company do?": "要让公司做什么？",
  "Use leader": "使用领导者",
  Brief: "任务说明",
  "Add context, constraints, or expected output.": "补充背景、约束或期望输出。",
  "Create task": "创建任务",
  Run: "运行",
  Review: "复核",
  Done: "完成",
  Changes: "要求修改",
  Draft: "草稿",
  Ready: "待执行",
  Blocked: "阻塞",
  Running: "运行中",
  Completed: "已完成",
  Empty: "空",
  "Run timeline": "运行时间线",
  "Select a task": "选择任务",
  "Blocked by": "被依赖阻塞：",
  "Assigned to": "分配给",
  "No task selected.": "未选择任务。",
  "No runs yet.": "暂无运行。",
  "No logs yet": "暂无日志",
  Cancel: "取消",
  "OUI server is not connected. Company actions require OUI server.":
    "OUI 服务未连接。公司操作需要 OUI 服务。",
  "OUI API is not available (HTTP {status}).": "OUI 后端 API 不可用（HTTP {status}）。",
  "Task title is required.": "请先填写任务标题。",
  "Company name is required.": "请先填写公司名。",
  "Select an OpenClaw CEO first.": "请先选择一个 OpenClaw CEO。",
  "Company was not created.": "公司没有创建成功。",
  "Select a company first.": "请先选择一家公司。",
  "Company created: {name}": "已创建公司：{name}",
  "Company deleted: {name}": "已删除公司：{name}",
  "Task created: {title}": "已创建任务：{title}",
  "Run queued: {runId}": "已排队运行：{runId}",
  "Task is blocked.": "任务被阻塞。",
  "OUI company is unavailable.": "OUI 公司不可用。",
  "Follow up with {agent}": "让 {agent} 跟进",
  "Created from four-pane {index}: {session}": "来自四宫格 {index}：{session}",
  "Task created from pane {index}.": "已从第 {index} 个窗口创建任务。",
  "External adapter execution is disabled.": "外部 adapter 执行当前已禁用。",
  "Company sections": "公司分区",
  "Control room": "监控室",
  Monitor: "监控",
  "CEO private chat": "CEO 私聊",
  "Open CEO chat": "打开 CEO 私聊",
  "Open OUI chat": "打开 OUI 聊天",
  "Generate runbook draft": "生成运行文档草稿",
  "Talk with the CEO to shape company direction.": "和 CEO 聊公司方向。",
  "Tell the CEO what this company should think about next.": "告诉 CEO 这家公司接下来要思考什么。",
  "Send to CEO": "发送给 CEO",
  "Execution plan": "执行计划",
  "Current execution plan": "当前执行计划",
  "Text version": "文字版",
  "Flowchart version": "流程图版",
  "Plan steps": "计划步骤",
  "Decision points": "决策点",
  "No decision points.": "暂无决策点。",
  "No execution plan yet.": "还没有执行计划",
  "Chat with the CEO, generate a runbook draft, then confirm it to see the plan here.":
    "先和 CEO 聊出方向，生成并确认运行文档后，这里会显示计划。",
  "Step {index}": "步骤 {index}",
  "No summary.": "暂无说明。",
  You: "你",
  "Message is required.": "请先输入消息。",
  "Runbook draft created: {title}": "已生成运行文档草稿：{title}",
  "Runbook started: {title}": "已启动运行文档：{title}",
  "Inbox center": "收件箱",
  Runbook: "运行文档",
  Runbooks: "运行文档",
  Organization: "组织结构",
  Artifacts: "成果仓库",
  Settings: "设置",
  "Current objective": "当前目标",
  "Current stage": "当前阶段",
  "Open inbox": "待处理",
  "Active runbook": "生效运行文档",
  "Next step": "下一步",
  "No runbook approved yet.": "还没有确认过的运行文档。",
  "No active runbook yet.": "还没有已启动的运行文档。",
  "Talk to the CEO and approve a runbook before the company starts work.":
    "先和 CEO 聊清楚方向，并确认运行文档，公司才会开工。",
  "Review the open inbox items before the company continues.": "先处理收件箱里的待办事项。",
  "Company has an approved runbook. Execution is not started in P0.":
    "公司已有确认的运行文档，P0 阶段暂不自动执行。",
  "Confirm this runbook to create work nodes.": "确认这份运行文档后会生成工作节点。",
  "Runbook is active. First work node is ready.": "运行文档已激活，第一个工作节点已就绪。",
  "Runbook is active. Work nodes are running or ready.":
    "运行文档已启动，工作节点正在运行或已就绪。",
  "Runbook completed. Review the artifacts and CEO report.":
    "运行文档已完成，可以检查成果和 CEO 汇报。",
  "Watch current stage and wait for the next CEO report.": "观察当前阶段，等待 CEO 下一次汇报。",
  "No control-room nodes yet.": "监控室还没有运行节点。",
  "OpenClaw agent": "OpenClaw agent",
  "The CEO is the long-term company representative.": "CEO 是这家公司的长期代表。",
  "No inbox items.": "收件箱暂无待处理事项。",
  Approve: "通过",
  Reply: "回复",
  "Reply to the CEO": "回复 CEO",
  "Why should this be changed?": "说明需要修改的原因",
  Reject: "打回",
  Stop: "停止",
  Continue: "继续",
  "Inbox item handled: {title}": "已处理收件箱事项：{title}",
  "Approval recorded. Company is continuing the next work node.":
    "已通过，公司正在继续推进下一个工作节点。",
  "Approval recorded. Another inbox item needs your decision.":
    "已通过，还有新的收件箱事项需要你处理。",
  "Approval recorded, but the company is blocked. Check inbox.":
    "已通过，但公司仍有阻塞，请检查收件箱。",
  "Runbook completed after approval. Continue with the CEO for the next direction.":
    "已通过，当前运行文档已完成。接下来可以和 CEO 继续聊下一轮方向。",
  "This runbook is complete. Review artifacts or continue with the CEO for the next direction.":
    "当前运行文档已完成。可以检查成果，或继续和 CEO 聊下一轮方向。",
  "Save output": "保存成果",
  "Run node": "运行节点",
  "Sync progress": "同步进度",
  "Marked complete from control room.": "已在监控室标记完成。",
  "Work node completed: {title}": "工作节点已完成：{title}",
  "Work node run blocked: {title}": "节点运行受阻：{title}",
  "Active version": "当前版本",
  "Version {version}": "版本 {version}",
  Source: "来源",
  Stages: "阶段",
  "No stages yet.": "还没有阶段。",
  "No runbooks yet.": "还没有运行文档。",
  "No runbook drafts yet.": "还没有运行文档草稿。",
  "Confirm and start": "确认并开始",
  "Restart runbook": "重新运行",
  "Work nodes": "工作节点",
  Routines: "常驻业务",
  Routine: "常驻业务",
  "Recurring runbooks wake up and create normal company work.":
    "常驻业务会定时醒来，并转成普通公司工作继续执行。",
  Trigger: "触发",
  Policy: "策略",
  "Next trigger": "下次触发",
  "Trigger now": "立即触发",
  "Pause routine": "暂停常驻业务",
  "Resume routine": "恢复常驻业务",
  "Create daily routine": "创建每日常驻业务",
  "No routines yet.": "还没有常驻业务。",
  "Routine created: {title}": "已创建常驻业务：{title}",
  "Routine triggered: {title}": "已触发常驻业务：{title}",
  "Routine paused: {title}": "已暂停常驻业务：{title}",
  "Routine resumed: {title}": "已恢复常驻业务：{title}",
  "company.created": "公司已创建",
  "runbook.draft_created": "运行文档草稿已创建",
  "runbook.approved": "运行文档已确认",
  "runbook.started": "运行文档已启动",
  "routine.created": "常驻业务已创建",
  "routine.triggered": "常驻业务已触发",
  "routine.active": "常驻业务已启用",
  "routine.paused": "常驻业务已暂停",
  "routine.disabled": "常驻业务已禁用",
  "inbox.approve": "收件箱已通过",
  "inbox.reject": "收件箱已打回",
  "inbox.reply": "收件箱已回复",
  "inbox.stop": "收件箱已停止",
  schedule: "定时",
  api: "API",
  webhook: "Webhook",
  skip_if_active: "忙时跳过",
  coalesce_if_active: "忙时合并",
  always_enqueue: "总是排队",
  "CoS / Operations": "CoS / 总裁办",
  Coordinator: "调度中枢",
  "Artifact repository": "成果仓库",
  "No artifacts yet.": "还没有成果。",
  "Meeting room": "会议室",
  "Global free-agent meetings": "自由 agent 会议室",
  Meetings: "会议",
  Ended: "已结束",
  Minutes: "纪要",
  Meeting: "会议",
  "Create meeting": "创建会议",
  "Meeting title": "会议标题",
  Agent: "Agent",
  "Connect Gateway to choose agents": "连接 Gateway 后选择 agent",
  Invite: "邀请",
  "Invite agent": "邀请 agent",
  "Invite selected agent": "邀请已选 agent",
  "Choose an agent to add to this meeting.": "选择一个 agent 加入这场会议。",
  Objective: "目标",
  Description: "描述",
  "What should this meeting discuss?": "这次会议要讨论什么？",
  "No agents invited yet.": "还没有邀请 agent。",
  "No available agents to invite.": "没有可邀请的 agent。",
  "New meeting": "新会议",
  "Invited agents": "已邀请 agent",
  "Name the meeting, invite agents on the left, then write the objective here.":
    "先给会议命名，在左边邀请 agent，然后在这里写本次会议目标。",
  "Use the left panel to set the meeting title, description, and invited agents.":
    "在左侧面板设置会议标题、描述和邀请的 agent。",
  "Add a meeting title before starting.": "请先填写会议标题。",
  "In meeting": "会议中",
  Participants: "参会成员",
  "Agent management": "Agent 管理",
  "Speaking order": "发言顺序",
  Order: "顺位",
  Muted: "已闭麦",
  "Mic on": "开麦",
  "Mic off": "闭麦",
  "Move earlier": "提前",
  "Move later": "延后",
  Remove: "移出",
  "Meeting notes": "会议纪要",
  "No meeting notes yet.": "还没有会议纪要。",
  "Meeting has ended.": "会议已结束。",
  "Meeting history": "会议记录",
  Agents: "Agent",
  "No objective set.": "还没有目标。",
  "No meetings yet.": "还没有会议。",
  "Select or create a meeting.": "选择或创建一个会议。",
  Start: "开始",
  End: "结束",
  "Generate minutes": "生成纪要",
  "No meeting messages yet.": "还没有会议消息。",
  "Send an agenda item to the meeting.": "给会议发送一个议题。",
  Send: "发送",
  System: "系统",
  "Meeting title is required.": "请先填写会议标题。",
  "Meeting was not created.": "会议创建失败。",
  "Meeting created: {title}": "已创建会议：{title}",
  "Meeting prompt is required.": "请先输入会议议题。",
  "Meeting minutes generated: {title}": "已生成会议纪要：{title}",
  stage_output: "阶段输出",
  resolved: "已处理",
  rejected: "已打回",
  stopped: "已停止",
  Updated: "更新",
  "Stage {index}": "阶段 {index}",
  ceo_chat: "CEO 私聊",
  meeting_minutes: "会议纪要",
  imported_markdown: "导入 Markdown",
  manual: "手动",
  choice: "选择",
  approval: "审批",
  revision: "打回修改",
  exception: "异常",
  report_ack: "阶段确认",
  queued: "排队中",
  current: "当前",
  draft: "草稿",
  ready: "待执行",
  pending: "待排队",
  blocked: "阻塞",
  running: "运行中",
  review: "复核",
  done: "完成",
  skipped: "已跳过",
  active: "启用",
  completed: "已完成",
  disabled: "已禁用",
  none: "未提交",
  requested: "待复核",
  approved: "已批准",
  "changes requested": "要求修改",
  missing: "缺失",
  unknown: "未知",
  "Agent settings": "Agent 设置",
  "Adjust agent meeting preferences.": "调整这个 agent 在会议中的偏好设置。",
  "Thinking intensity": "思考强度",
  Low: "低",
  Medium: "中",
  High: "高",
  Close: "关闭",
  "Use the left panel for title, description, and speaking order. Manage agent cards below.":
    "左侧设置标题、描述和发言顺序，下方模块管理 agent 卡片。",
  Moderator: "主持人",
  "Moderator document": "主持人文档",
  "Discussion document": "讨论文档",
  "Save document": "保存文档",
  "Run next round": "进行下一轮",
  "Start round 1": "开始第 1 轮",
  "Awaiting user": "等待用户",
  "Use this box to tell the moderator what to change before the next round.":
    "在这里告诉主持人下一轮前要如何调整文档。",
  "Create the meeting first, then talk to the moderator between rounds.":
    "先创建会议，再在轮次之间和主持人交互。",
  "Moderator document saved.": "主持人文档已保存。",
  "Moderator document updated.": "主持人文档已更新。",
  "Round {round} completed.": "第 {round} 轮已完成。",
  not_found: "未找到对应会议，请刷新后重试。",
  meeting_ended: "会议已结束，无法继续下一轮。",
} as const;

type OuiCompanyCopyParams = Record<string, string | number | null | undefined>;

function interpolate(template: string, params?: OuiCompanyCopyParams): string {
  if (!params) {
    return template;
  }
  return template.replace(/\{(\w+)\}/g, (match, key) => {
    const value = params[key];
    return value == null ? match : String(value);
  });
}

export function ouiCompanyCopy(text: string | null | undefined, params?: OuiCompanyCopyParams) {
  if (!text) {
    return "";
  }
  const localized = isZhCnConfigCopy()
    ? (ZH_CN_OUI_COMPANY_COPY[text as keyof typeof ZH_CN_OUI_COMPANY_COPY] ??
      localizeConfigCopy(text))
    : text;
  return interpolate(localized, params);
}

export function ouiCompanyStatusLabel(value: string | null | undefined): string {
  return ouiCompanyCopy((value ?? "unknown").replace(/_/g, " "));
}

export function formatOuiCompanyError(error: unknown): string {
  const message = error instanceof Error ? error.message : String(error);
  const apiFailure = /^OUI API request failed: (\d+)$/.exec(message);
  if (apiFailure) {
    return ouiCompanyCopy("OUI API is not available (HTTP {status}).", {
      status: apiFailure[1],
    });
  }
  return ouiCompanyCopy(message);
}
