import { localizeConfigCopy, isZhCnConfigCopy } from "../i18n/lib/config-copy.ts";

const ZH_CN_OUI_COMPANY_COPY = {
  Company: "公司",
  "Company dashboard": "公司总看板",
  "Company, tasks, and run timeline": "公司、任务和运行时间线",
  "OUI Company": "OUI 公司",
  "Refreshing...": "正在刷新...",
  Refresh: "刷新",
  "Four-pane chat": "四宫格聊天",
  Companies: "公司",
  "Your AI companies": "我的 AI 公司",
  "New company": "新公司",
  "Company name": "公司名",
  "Create company": "创建公司",
  "Connect Gateway to choose CEO": "连接 Gateway 后选择 CEO",
  "Waiting for you": "待你处理",
  "Last activity": "最近活动",
  CEO: "CEO",
  Stage: "阶段",
  Status: "状态",
  Mode: "模式",
  Inbox: "收件箱",
  "Not set": "未设置",
  "No active objective yet.": "还没有主线目标",
  "No companies yet.": "暂无公司",
  "Internal records": "内部记录",
  "Task workbench": "任务工作台",
  Idle: "空闲",
  project: "项目型",
  routine: "常驻业务",
  idle: "空闲",
  waiting_user: "待你处理",
  "waiting user": "待你处理",
  paused: "暂停",
  Leader: "领导者",
  Tasks: "任务",
  Runs: "运行",
  "OUI server": "OUI 服务",
  Connected: "已连接",
  Disconnected: "未连接",
  Unassigned: "未分配",
  Active: "启用",
  Executable: "可执行",
  Disabled: "已禁用",
  "OpenClaw-led agents": "OpenClaw 主导的 agent",
  "No agents yet.": "暂无 agent。",
  Task: "任务",
  "Create work": "创建工作",
  Title: "标题",
  Assignee: "负责人",
  "What should the company do?": "要让公司做什么？",
  "Use leader": "使用领导者",
  Brief: "任务说明",
  "Add context, constraints, or expected output.": "补充背景、约束或期望输出。",
  "Create task": "创建任务",
  Run: "运行",
  Review: "复核",
  Done: "完成",
  Changes: "要求修改",
  Draft: "草稿",
  Ready: "待执行",
  Blocked: "阻塞",
  Running: "运行中",
  Completed: "已完成",
  Empty: "空",
  "Run timeline": "运行时间线",
  "Select a task": "选择任务",
  "Blocked by": "被依赖阻塞：",
  "Assigned to": "分配给",
  "No task selected.": "未选择任务。",
  "No runs yet.": "暂无运行。",
  "No logs yet": "暂无日志",
  "OUI server is not connected. Company actions require OUI server.":
    "OUI 服务未连接。公司操作需要 OUI 服务。",
  "OUI API is not available (HTTP {status}).": "OUI 后端 API 不可用（HTTP {status}）。",
  "Task title is required.": "请先填写任务标题。",
  "Company name is required.": "请先填写公司名。",
  "Select an OpenClaw CEO first.": "请先选择一个 OpenClaw CEO。",
  "Company was not created.": "公司没有创建成功。",
  "Select a company first.": "请先选择一家公司。",
  "Company created: {name}": "已创建公司：{name}",
  "Task created: {title}": "已创建任务：{title}",
  "Run queued: {runId}": "已排队运行：{runId}",
  "Task is blocked.": "任务被阻塞。",
  "OUI company is unavailable.": "OUI 公司不可用。",
  "Follow up with {agent}": "让 {agent} 跟进",
  "Created from four-pane {index}: {session}": "来自四宫格 {index}：{session}",
  "Task created from pane {index}.": "已从第 {index} 个窗口创建任务。",
  "External adapter execution is disabled.": "外部 adapter 执行当前已禁用。",
  "Company sections": "公司分区",
  "Control room": "监控室",
  Monitor: "监控",
  "CEO private chat": "CEO 私聊",
  "Open CEO chat": "打开 CEO 私聊",
  "Open OUI chat": "打开 OUI 聊天",
  "Generate runbook draft": "生成运行文档草稿",
  "Talk with the CEO to shape company direction.": "和 CEO 聊公司方向。",
  "Tell the CEO what this company should think about next.": "告诉 CEO 这家公司接下来要思考什么。",
  "Send to CEO": "发送给 CEO",
  You: "你",
  "Message is required.": "请先输入消息。",
  "Runbook draft created: {title}": "已生成运行文档草稿：{title}",
  "Runbook started: {title}": "已启动运行文档：{title}",
  "Inbox center": "收件箱",
  Runbook: "运行文档",
  Runbooks: "运行文档",
  Organization: "组织结构",
  Artifacts: "成果仓库",
  Settings: "设置",
  "Current objective": "当前目标",
  "Current stage": "当前阶段",
  "Open inbox": "待处理",
  "Active runbook": "生效运行文档",
  "Next step": "下一步",
  "No runbook approved yet.": "还没有确认过的运行文档。",
  "No active runbook yet.": "还没有已启动的运行文档。",
  "Talk to the CEO and approve a runbook before the company starts work.":
    "先和 CEO 聊清楚方向，并确认运行文档，公司才会开工。",
  "Review the open inbox items before the company continues.": "先处理收件箱里的待办事项。",
  "Company has an approved runbook. Execution is not started in P0.":
    "公司已有确认的运行文档，P0 阶段暂不自动执行。",
  "Confirm this runbook to create work nodes.": "确认这份运行文档后会生成工作节点。",
  "Runbook is active. First work node is ready.": "运行文档已激活，第一个工作节点已就绪。",
  "Watch current stage and wait for the next CEO report.": "观察当前阶段，等待 CEO 下一次汇报。",
  "No control-room nodes yet.": "监控室还没有运行节点。",
  "OpenClaw agent": "OpenClaw agent",
  "The CEO is the long-term company representative.": "CEO 是这家公司的长期代表。",
  "No inbox items.": "收件箱暂无待处理事项。",
  Approve: "通过",
  Reply: "回复",
  Reject: "打回",
  Stop: "停止",
  Continue: "继续",
  "Inbox item handled: {title}": "已处理收件箱事项：{title}",
  "Save output": "保存成果",
  "Marked complete from control room.": "已在监控室标记完成。",
  "Work node completed: {title}": "工作节点已完成：{title}",
  "Active version": "当前版本",
  "Version {version}": "版本 {version}",
  Source: "来源",
  Stages: "阶段",
  "No stages yet.": "还没有阶段。",
  "No runbooks yet.": "还没有运行文档。",
  "No runbook drafts yet.": "还没有运行文档草稿。",
  "Confirm and start": "确认并开始",
  "Work nodes": "工作节点",
  "Artifact repository": "成果仓库",
  "No artifacts yet.": "还没有成果。",
  "Meeting room": "会议室",
  "Global free-agent meetings": "自由 agent 会议室",
  Meetings: "会议",
  Ended: "已结束",
  Minutes: "纪要",
  Meeting: "会议",
  "Create meeting": "创建会议",
  "Meeting title": "会议标题",
  Agent: "Agent",
  "Connect Gateway to choose agents": "连接 Gateway 后选择 agent",
  Invite: "邀请",
  Objective: "目标",
  "What should this meeting discuss?": "这次会议要讨论什么？",
  "No agents invited yet.": "还没有邀请 agent。",
  "Meeting history": "会议记录",
  Agents: "Agent",
  "No objective set.": "还没有目标。",
  "No meetings yet.": "还没有会议。",
  "Select or create a meeting.": "选择或创建一个会议。",
  Start: "开始",
  End: "结束",
  "Generate minutes": "生成纪要",
  "No meeting messages yet.": "还没有会议消息。",
  "Send an agenda item to the meeting.": "给会议发送一个议题。",
  Send: "发送",
  System: "系统",
  "Meeting title is required.": "请先填写会议标题。",
  "Meeting was not created.": "会议创建失败。",
  "Meeting created: {title}": "已创建会议：{title}",
  "Meeting prompt is required.": "请先输入会议议题。",
  "Meeting minutes generated: {title}": "已生成会议纪要：{title}",
  stage_output: "阶段输出",
  resolved: "已处理",
  rejected: "已打回",
  stopped: "已停止",
  Updated: "更新",
  "Stage {index}": "阶段 {index}",
  ceo_chat: "CEO 私聊",
  meeting_minutes: "会议纪要",
  imported_markdown: "导入 Markdown",
  manual: "手动",
  choice: "选择",
  approval: "审批",
  revision: "打回修改",
  exception: "异常",
  report_ack: "阶段确认",
  queued: "排队中",
  current: "当前",
  draft: "草稿",
  ready: "待执行",
  pending: "待排队",
  blocked: "阻塞",
  running: "运行中",
  review: "复核",
  done: "完成",
  skipped: "已跳过",
  active: "启用",
  completed: "已完成",
  disabled: "已禁用",
  none: "未提交",
  requested: "待复核",
  approved: "已批准",
  "changes requested": "要求修改",
  missing: "缺失",
  unknown: "未知",
} as const;

type OuiCompanyCopyParams = Record<string, string | number | null | undefined>;

function interpolate(template: string, params?: OuiCompanyCopyParams): string {
  if (!params) {
    return template;
  }
  return template.replace(/\{(\w+)\}/g, (match, key) => {
    const value = params[key];
    return value == null ? match : String(value);
  });
}

export function ouiCompanyCopy(text: string | null | undefined, params?: OuiCompanyCopyParams) {
  if (!text) {
    return "";
  }
  const localized = isZhCnConfigCopy()
    ? (ZH_CN_OUI_COMPANY_COPY[text as keyof typeof ZH_CN_OUI_COMPANY_COPY] ??
      localizeConfigCopy(text))
    : text;
  return interpolate(localized, params);
}

export function ouiCompanyStatusLabel(value: string | null | undefined): string {
  return ouiCompanyCopy((value ?? "unknown").replace(/_/g, " "));
}

export function formatOuiCompanyError(error: unknown): string {
  const message = error instanceof Error ? error.message : String(error);
  const apiFailure = /^OUI API request failed: (\d+)$/.exec(message);
  if (apiFailure) {
    return ouiCompanyCopy("OUI API is not available (HTTP {status}).", {
      status: apiFailure[1],
    });
  }
  return ouiCompanyCopy(message);
}
